sudo: required
dist: trusty

language: php
php:
  - 5.5
  - 5.6
  - 7

env:
  - DB=1.7.1 ES_PKG=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.1.deb
  - DB=2.2.0 ES_PKG=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.2.0/elasticsearch-2.2.0.deb
  - DB=5.3.2 ES_PKG=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.2.deb

before_install:
  - curl -O $ES_PKG && sudo dpkg -i --force-confnew $(printf 'elasticsearch-%s.deb' $DB)
  - sudo service elasticsearch start
  - until curl localhost:9200; do sleep 1; done

install:
  # Make sure old ES versions use the old ES lib. ES lib 5.0+ is not compatible with old ES versions
  - sh -c "if [ '$DB' = '1.7.1' ]; then sed -i 's/<6.0/<5.0/' composer.json; fi"
  - sh -c "if [ '$DB' = '2.2.0' ]; then sed -i 's/<6.0/<5.0/' composer.json; fi"
  - composer install

script: ./vendor/bin/phpunit --coverage-text

notifications:
  email: false
